on:
  workflow_call:
    inputs:
      private-feed:
        description: Use a private NPM feed?
        required: false
        type: string
        default: "true"
      feed:
        description: Project in Azure artifacts
        required: false
        type: string
        default: "JayTechUI"
      organization:
        description: Organization in Azure artifacts
        required: false
        type: string
        default: "JayTechIT"
      project:
        description: Scope for package
        required: false
        type: string
        default: "JayTech"
      scope:
        description: Scope for package
        required: false
        type: string
        default: "jaytech"
    secrets:
      azure-api-key:
        description: The Azure API key
        required: false
      azure-feed:
        description: The Azure Artifacts Feed
        required: false
      azure-source:
        description: The Azure Artifacts Source
        required: false
      pat-github:
        description: GitHub PAT
        required: true

jobs:
  npm-package-pipeline:
    name: NPM Package Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
          fetch-depth: 0
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechIT/jaytech-pipelines-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - id: semver
        uses: ./workflow/actions/gitversion-semver
      - name: Replace package version
        run: |
          sed -i "s#{{PACKAGE_VERSION}}#${{ steps.semver.outputs.semantic-version }}#g" ./workflow/repository/package.json
          sed -i "s#{{ORGANIZATION_NAME}}#${{ inputs.organization }}#g" ./workflow/repository/.npmrc
          sed -i "s#{{PROJECT_NAME}}#${{ inputs.project }}#g" ./workflow/repository/.npmrc
          sed -i "s#{{FEED_NAME}}#${{ inputs.feed }}#g" ./workflow/repository/.npmrc
          sed -i "s#{{TOKEN}}#${{ secrets.azure-api-key }}#g" ./workflow/repository/.npmrc
          cat ./workflow/repository/.npmrc
      - name: Copy .npmrc to home directory
        run: cp ./workflow/repository/.npmrc ~/.npmrc
      - name: Set NPM registry for scope
        run: npm config set @${{inputs.scope}}:registry ${{secrets.azure-feed}}
      - name: Debug .npmrc
        run: |
          echo "=== .npmrc ==="
          cat ~/.npmrc
          echo "============="
      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.azure-api-key }}
        working-directory: ./workflow/repository/
      - name: Publish to Azure Artifacts
        working-directory: ./workflow/repository/
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.azure-api-key }}
      - name: Tag & Release
        uses: actions/create-release@v1
        if: contains('refs/heads/master', github.ref)
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.semver.outputs.semantic-version }}
          tag_name: ${{ steps.semver.outputs.semantic-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
