on:
  workflow_call:
    inputs:
      private-feed:
        description: Use a private NPM feed?
        required: false
        type: string
        default: "true"
      organization:
        description: Organization in Azure artifacts
        required: false
        type: string
        default: "JayTechIT"
      project:
        description: Project in Azure artifacts
        required: false
        type: string
        default: "JayTechUI"
      scope:
        description: Scope for package
        required: false
        type: string
        default: "jaytech"
    secrets:
      azure-api-key:
        description: The Azure API key
        required: false
      azure-feed:
        description: The Azure Artifacts Feed
        required: false
      azure-source:
        description: The Azure Artifacts Source
        required: false
      pat-github:
        description: GitHub PAT
        required: true

jobs:
  npm-package-pipeline:
    name: NPM Package Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
          fetch-depth: 0
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechIT/jaytech-pipelines-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: ${{secrets.azure-feed}}
      - id: semver
        uses: ./workflow/actions/gitversion-semver
      - name: Replace package version
        working-directory: ./workflows/repository
        run: |
          sed -i "s/{{PACKAGE_VERSION}}/${{ steps.semver.outputs.semantic-version }}/g" package.json
          sed -i "s/{{FEED}}/${{ secrets.azure-feed }}/g" .npmrc
          sed -i "s/{{SCOPE}}/${{ inputs.scope }}/g" .npmrc
          sed -i "s/{{USER}}/${{ inputs.organization }}/g" .npmrc
          sed -i "s/{{PASSWORD}}/${{ secrets.azure-api-key }}/g" .npmrc
          sed -i "s/{{EMAIL}}/a@a.a/g" .npmrc

          cp ./workflows/repository/.npmrc ~/.npmrc
          npm install
          npm publish

      - run: cp `pwd`/.npmrc ~ # We need the .npmrc file in the $HOME directory
