on:  
  workflow_call:
    inputs:
      namespace:
        type: string
        description: The application name (repository name without api/contract/ui)
        required: true
    secrets:
      pat-github:
        description: GitHub PAT
        required: true
      azure-api-key:
        description: The Azure API key
        required: false
      azure-source:
        description: The Azure Artifacts Source
        required: false
      azure-feed:
        description: The Azure Artifacts Feed
        required: false
jobs:
  build-push-oas:
    name: Build + NuGet push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat-github }}
          path: workflow/repository
          fetch-depth: 0
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechIT/jaytech-pipelines-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - name: Add Azure feed
        shell: bash
        run: dotnet nuget add source ${{ secrets.azure-feed }} --name ${{secrets.azure-source}} --username az --password ${{ secrets.azure-api-key }} --store-password-in-clear-text 
      - id: semver
        name: Determine semantic version
        uses: ./workflow/actions/gitversion-semver
      - name: Set contract version
        run: sed -i "s/{{OAS_VERSION}}/${{ steps.semver.outputs.semantic-version }}/g" ./workflow/repository/src/oas.yaml
      - name: Checkout client generator
        uses: actions/checkout@v3
        with:
          repository: JayTechIT/jaytech-tools-clis-generators-client
          token: ${{ secrets.pat-github }}
          path: workflow/client-generator
          fetch-depth: 0
      - name: Run Client Generator
        shell: bash
        run: |
          sed -i "s~{{IN}}~../../../../../workflow/repository/src/oas.yaml~g" ./workflow/client-generator/Source/Assemblies/JayTech.Tools.ClientGeneration.Cli/Properties/launchSettings.json
          sed -i "s~{{OUT}}~../../../../../workflow/repository/generated~g" ./workflow/client-generator/Source/Assemblies/JayTech.Tools.ClientGeneration.Cli/Properties/launchSettings.json
          sed -i "s~{{NAMESPACE}}~${{inputs.namespace}}~g" ./workflow/client-generator/Source/Assemblies/JayTech.Tools.ClientGeneration.Cli/Properties/launchSettings.json
          cd ./workflow/client-generator/Source/Assemblies/JayTech.Tools.ClientGeneration.Cli
          dotnet run --launch-profile Production
          ls -A
      - name: nuget-push
        uses: ./workflow/actions/dotnet-publish-nuget
        with:
          software-version: ${{ steps.semver.outputs.semantic-version }}
          project-folder: ./workflow/repository/generated
          azure-api-key: ${{secrets.azure-api-key}}
          azure-source: ${{secrets.azure-source}}
          azure-feed: ${{secrets.azure-feed}}