on:
  workflow_call:
    inputs:
      application-name:
        type: string
        description: The application name (repository name without api/contract/ui)
        required: true
      environment-name:
        type: string
        description: The keyword used to define your environment repository
        required: false
        default: environment
      build-web:
        type: boolean
        description: Run Quasar build for web?
        required: false
        default: false
      replacements-in:
        type: string
        description: Replacement placeholders separated by a semicolon (;)
        required: false
        default: ""
      source-folder:
        type: string
        description: Root folder of the source code
        required: false
        default: "./workflow/repository"
    secrets:
      pat-github:
        description: GitHub PAT
        required: true
      replacements-out:
        description: Replacement values separated by a semicolon (;)
        required: false

jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
          fetch-depth: 0
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechIT/jaytech-pipelines-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - name: Replace placeholders
        uses: ./workflow/actions/replace-placeholders
        with:
          replacements-in: ${{inputs.replacements-in}}
          replacements-out: ${{secrets.replacements-out}}
      - name: Upload prepared repository
        uses: actions/upload-artifact@v3
        with:
          name: workflow
          path: workflow
          retention-days: 2
  build-web:
    if: ${{inputs.build-web}}
    needs: preparations
    name: Build Quasar Web
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Quasar Build Web
        uses: ./workflow/actions/quasar-build-web
        with:
          folder: ${{inputs.source-folder}}
  
  continuous-delivery:
    if: ${{ always() }}
    needs: ["build-web"]
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Download web contents      
        uses: actions/download-artifact@v1      
        with:
          name: quasar-build-web
          path: ./output/web
      - name: TAR
        run: |
          tar -czvf ./output/web/quasar-web.tar.gz ./output/web/*
      - id: semver
        uses: ./workflow/actions/gitversion-semver
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.semver.outputs.semantic-version }}
          tag_name: ${{ steps.semver.outputs.semantic-version }}        
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
      - name: Upload quasar-web to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/web/quasar-web.tar.gz
          asset_name: quasar-web.tar.gz
          asset_content_type: application/gzip
  sync-environment:
    name: Sync Environment
    needs: continuous-delivery
    runs-on: ubuntu-latest
    if: ${{ inputs.sync-environment == 'true' }}
    steps:
      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          ref: "development"
          repository: ${{ github.repository_owner }}/${{ inputs.application-name }}-${{inputs.environment-name}}
          token: ${{secrets.pat-github}}
          path: workflow/gitops
      - name: Set GitOps version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "./workflow/gitops/version.yml"
          propertyPath: "version.ui"
          value: ${{inputs.software-version}}
          commitChange: false
          updateFile: true
      - name: Push to GitOps
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.pat-github }}
        with:
          source-directory: workflow/gitops
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ inputs.application-name }}-${{inputs.environment-name}}
          commit-message: Updated ${{ github.event.repository.name }} version to ${{inputs.software-version}}
          target-branch: development