name: Retrieve JayTech Secrets

on:
  workflow_call:
    inputs:
      secret-map:
        type: string
        required: true
    secrets:
      jaytech-credential-key:
        required: true
      pat-github:
        required: true

    outputs:
      pat-github:
        description: "Retrieved PAT"
        value: ${{ jobs.retrieve-secrets.outputs.pat-github }}
      replacements-out:
        description: "Base64 AZURE API key"
        value: ${{ jobs.retrieve-secrets.outputs.replacements-out }}
      key-store-password:
        description: "Keystore secret"
        value: ${{ jobs.retrieve-secrets.outputs.key-store-password }}

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    outputs:
      pat-github: ${{ steps.retrieve.outputs.pat-github }}
      replacements-out: ${{ steps.retrieve.outputs.replacements-out }}
      key-store-password: ${{ steps.retrieve.outputs.key-store-password }}
    steps:
      - name: Retrieve secrets dynamically
        id: retrieve
        uses: JayTechIT/jaytech-github-actions-retrieve-secrets@master
        with:
          jaytech-credential-key: ${{ secrets.jaytech-credential-key }}
          secret-map: ${{ inputs.secret-map }}
