# .github/workflows/retrieve-jaytech-secrets.yml
name: Retrieve JayTech Secrets

on:
  workflow_call:
    inputs:
      secret-map:
        type: string
        required: true
    secrets:
      jaytech-credential-key:
        required: true
      pat-github:
        required: true

    outputs:
      pat-github:
        description: "Retrieved PAT"
        value: ${{ jobs.retrieve-secrets.outputs.pat-github }}
      replacements-out:
        description: "Base64 AZURE API key"
        value: ${{ jobs.retrieve-secrets.outputs.replacements-out }}
      key-store-password:
        description: "Keystore secret"
        value: ${{ jobs.retrieve-secrets.outputs.key-store-password }}

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    outputs:
      pat-github: ${{ steps.retrieve.outputs.pat-github }}
      replacements-out: ${{ steps.retrieve.outputs.replacements-out }}
      key-store-password: ${{ steps.retrieve.outputs.key-store-password }}
    steps:
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechIT/jaytech-pipelines-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions

      - name: Retrieve secrets dynamically
        id: retrieve
        uses: ./workflow/actions/retrieve-jaytech-secrets-map
        with:
          jaytech-credential-key: ${{ inputs.jaytech-credential-key }}
          secret-map: ${{ inputs.secret-map }}
